apiVersion: v1
kind: Service
metadata:
  name: fixit-backend
  namespace: fixit
  labels:
    app: fixit-backend
spec:
  selector:
    app: fixit-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
