name: CI/CD Pipeline Java

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  MAVEN_VERSION: '3.9.5'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Check-in java version
        run: java -version

      - name: Tests
        run: mvn test

      - name: Packaging
        run: mvn package -DskipTests

      - name: Upload do artefato JAR
        uses: actions/upload-artifact@v4
        with:
          name: aplicacao-jar
          path: target/*.jar
          retention-days: 30